const tasksData = [
    {
        id: 1,
        title: 'Complete project proposal',
        description: 'Finish writing the project proposal and submit it by the end of the day.',
        dueDate: '2024-06-30',
        priority: 2,
        completed: false,
        createdAt: '2024-06-25T09:00:00',
    },
    {
        id: 2,
        title: 'Meeting with client',
        description: 'Schedule a meeting with the client to discuss project requirements and timelines.',
        dueDate: '2024-02-05',
        priority: 1,
        completed: false,
        createdAt: '2024-01-28T14:30:00',
    },
    {
        id: 3,
        title: 'Update website content',
        description: 'Review and update the content on the company website.',
        dueDate: '2024-02-10',
        priority: 3,
        completed: true,
        completedAt: '2024-02-08T11:45:00',
        createdAt: '2024-02-01T10:15:00',
    },
    {
        id: 4,
        title: 'Code review for new feature',
        description: 'Conduct a code review for the implementation of a new feature in the application.',
        dueDate: '2024-02-15',
        priority: 2,
        completed: false,
        createdAt: '2024-02-10T15:20:00',
    },
    {
        id: 5,
        title: 'Prepare presentation slides',
        description: 'Create presentation slides for the upcoming team meeting.',
        dueDate: '2024-02-20',
        priority: 1,
        completed: false,
        createdAt: '2024-02-15T12:30:00',
    },
    {
        id: 6,
        title: 'Review and respond to emails',
        description: 'Check and respond to emails in the inbox.',
        dueDate: '2024-02-25',
        priority: 3,
        completed: false,
        createdAt: '2024-02-20T09:45:00',
    },
    {
        id: 7,
        title: 'Setup team meeting',
        description: 'Schedule a team meeting to discuss ongoing projects and challenges.',
        dueDate: '2024-03-01',
        priority: 1,
        completed: false,
        createdAt: '2024-02-25T14:15:00',
    },
    {
        id: 8,
        title: 'Bug fixing and testing',
        description: 'Address reported bugs and perform testing on the application.',
        dueDate: '2024-03-05',
        priority: 2,
        completed: false,
        createdAt: '2024-03-01T11:30:00',
    },
    {
        id: 9,
        title: 'Social media content creation',
        description: 'Create engaging content for social media channels.',
        dueDate: '2024-03-10',
        priority: 3,
        completed: false,
        createdAt: '2024-03-05T13:20:00',
    },
    {
        id: 10,
        title: 'Monthly financial report',
        description: 'Prepare the monthly financial report for the accounting department.',
        dueDate: '2024-03-15',
        priority: 1,
        completed: false,
        createdAt: '2024-03-10T10:00:00',
    },
];

export default tasksData;
